# Generated by Django 5.2.14 on 2026-08-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, help_text="Unique identifier sent in X-USER-ID header (e.g., 'friend1' or 'admin').", max_length=50, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable display name.', max_length=100)),
                ('api_key', models.CharField(db_index=True, help_text='Secret API key sent in X-API-KEY header.', max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this user is allowed to authenticate and message.')),
                ('profile_photo', models.ImageField(blank=True, help_text='Optional profile photo.', null=True, upload_to='profiles/')),
            ],
            options={
                'verbose_name': 'Chat User',
                'verbose_name_plural': 'Chat Users',
                'ordering': ['display_name'],
            },
        ),
    ]
