# Generated by Django 5.2.14 on 2026-08-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='fcm_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
