# Generated by Django 5.2.17 on 2026-09-06 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=32)),
                ('passcode', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nick_name'],
            },
        ),
        migrations.CreateModel(
            name='GallerySite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nick_name', models.CharField(max_length=120)),
                ('occasion_date', models.DateField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_current', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='gallery.galleryperson')),
            ],
            options={
                'ordering': ['sort_order', '-occasion_date', '-created_at'],
            },
        ),
    ]
