# Generated by Django 5.2.17 on 2026-09-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_seed_default_and_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryperson',
            name='api_key',
            field=models.CharField(blank=True, default='', help_text='Optional ChatUser API key (e.g. apk-key-abc-123) enabling chat for this person.', max_length=128),
        ),
    ]
