# Generated by Django 5.2.14 on 2026-08-04 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('SYSTEM', 'System')], default='TEXT', help_text='Type of message (TEXT, IMAGE, SYSTEM).', max_length=10)),
                ('text', models.TextField(blank=True, default='', help_text='Text content of the message.')),
                ('image', models.ImageField(blank=True, help_text='Optional image attachment.', null=True, upload_to='messages/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when message was created.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seen', models.BooleanField(default=False, help_text='Whether the receiver has seen this message.')),
                ('delivered', models.BooleanField(default=False, help_text='Whether the receiver has received this message.')),
                ('deleted_by_admin', models.BooleanField(default=False, help_text='Whether the admin has soft-deleted this message.')),
                ('deleted_by_user', models.BooleanField(default=False, help_text='Whether the user has soft-deleted this message.')),
                ('receiver', models.ForeignKey(help_text='Receiver of the message.', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='users.chatuser')),
                ('sender', models.ForeignKey(help_text='Sender of the message.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='users.chatuser')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
