# Generated by Django 5.2.14 on 2026-08-25 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('users', '0002_chatuser_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='Content of the memo.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('seen', models.BooleanField(default=False, help_text='Whether the admin has read this memo.')),
                ('sender', models.ForeignKey(help_text='The ChatUser who submitted this memo.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_memos', to='users.chatuser')),
            ],
            options={
                'verbose_name': 'Memo',
                'verbose_name_plural': 'Memos',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
