# Generated by Django 5.2.17 on 2026-08-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image attachment.', null=True, upload_to='memos/'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='text',
            field=models.TextField(blank=True, default='', help_text='Content of the memo.'),
        ),
    ]
