# Generated by Django 5.2.17 on 2026-09-15 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_memo_image_alter_memo_text'),
        ('users', '0002_chatuser_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable group name.', max_length=100)),
                ('slug', models.SlugField(help_text='Unique group slug identifier for URLs and API calls.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description.')),
                ('icon', models.ImageField(blank=True, help_text='Optional group icon.', null=True, upload_to='group_icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this group is active.')),
            ],
            options={
                'verbose_name': 'Chat Group',
                'verbose_name_plural': 'Chat Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('SYSTEM', 'System')], default='TEXT', max_length=10)),
                ('text', models.TextField(blank=True, default='', help_text='Group message content.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='group_messages/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatgroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_group_messages', to='users.chatuser')),
            ],
            options={
                'verbose_name': 'Group Message',
                'verbose_name_plural': 'Group Messages',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(default=False, help_text='Group admin flag.')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_message_id', models.BigIntegerField(default=0, help_text='Tracks the highest message ID read by this member.')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chat.chatgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='users.chatuser')),
            ],
            options={
                'verbose_name': 'Group Membership',
                'verbose_name_plural': 'Group Memberships',
                'ordering': ['joined_at'],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PeerChatPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('peer', models.ForeignKey(help_text='The peer user they are allowed to message.', on_delete=django.db.models.deletion.CASCADE, related_name='allowed_by_peers', to='users.chatuser')),
                ('user', models.ForeignKey(help_text='The user granted permission to chat.', on_delete=django.db.models.deletion.CASCADE, related_name='allowed_peers', to='users.chatuser')),
            ],
            options={
                'verbose_name': 'Peer Chat Permission',
                'verbose_name_plural': 'Peer Chat Permissions',
                'ordering': ['user__display_name', 'peer__display_name'],
                'unique_together': {('user', 'peer')},
            },
        ),
    ]
